services:
  - type: web
    name: pro-doge-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    autoDeploy: true
    envVars:
      - key: BINGX_API_KEY
        sync: false
      - key: BINGX_API_SECRET
        sync: false
    healthCheckPath: /
